### ISSUE TITLE
Combat tracker doesn't add more than 2 characters

### ISSUE THREAD

**Issue by Gerolencia** [Orcpub/orcpub#263]
**Describe the bug**
I try to add more players to the combat and it doesn't seems to work. Same occurs to adding a party; only one character is added to the combat.

**Comment by codeGlaze** [comment]
I can't recreate this error.

Mobile or PC?
Which OS?
Which Browser?

Are you using any uploaded brew files?
Have you tried incognito?

**Comment by datdamnzotz** [comment]
Unanswered response. Closing

**Comment by polyonymous** [comment]
I am commenting because I had the same issue as described above, but I'm not requesting this be reopened, just providing an answer for anyone else who finds this the way I did when seeking a solution.

The combat tracker will only add characters that are "AL legal" - ie, if you go into the "edit" page of a character and it has the red cross mark and "AL illegal" at the top, you need to address the reasons given before you can use that character in the combat tracker.

Additional info in case its useful to anyone:
using a PC
OS = Linux (arch)
Browser = Firefox (up to date)
I was using uploaded brew files for monsters, which were added in the tracker as expected.
Trying incognito mode didn't fix the issue.
