### ISSUE TITLE
Bug: only one selection for subrace and archetype

### ISSUE THREAD

**Issue by sonofbabar** [Orcpub/orcpub#303]
Hi there,

I'm using the DMV character creator and found that for my level 5 gnome rogue only one subrace (rock gnome) and roguish archetype or are available. Also for subtype, it says level 3 rogue when I'm clearly a level 5 rogue. 
![screen_archetype](https://user-images.githubusercontent.com/60438643/73371685-067a0e00-4284-11ea-978e-e666d2bdcc53.PNG)
![screen_subrace](https://user-images.githubusercontent.com/60438643/73371686-067a0e00-4284-11ea-8b20-ace35016f252.PNG)
Strangely enough, when I look at the character list, it has the correct subrace and roguish archetype, but the spell list is blank among other things as if I never selected either.
![screen_characterlist](https://user-images.githubusercontent.com/60438643/73372216-d67f3a80-4284-11ea-9d86-3a2ea48cb52a.PNG)

Is this a bug, or am I doing something wrong?

**Comment by DivertedCircle** [comment]
The problems you're encountering are because you have no custom content loaded. The website is only allowed to host content that WotC has released in the 5th Edition System Reference Document (SRD). In this case, that is only the rock gnome subrace and Thief archetype for rogues.

It is showing third level because that is when you choose your Rogue subclass. The spell list is blank because you do not have any spells as either a Thief or a Rock Gnome.

**Comment by DivertedCircle** [comment]
You can look for custom content on the Discord server or make it yourself.
https://discord.gg/ugG6zJ

**Comment by sonofbabar** [comment]
Thank you this makes perfect sense!
