### ISSUE TITLE
Missing Tempest Domain Spell

### ISSUE THREAD

**Issue by gadams168** [Orcpub/orcpub#322]
For a Tempest Domain Cleric, the 9th level (5th on DMV) is missing Destructive Wave.

**Comment by DivertedCircle** [comment]
Tempest Clerics aren't included in the SRD so this isn't an issue with the website. Rather, it is an issue with an orcbrew file you have loaded. You can edit the file yourself to fix it, or there will be an updated version on the Discord server shortly. Future bugs like this, concerning orcbrews instead of the website, should be posted in the #orcbrew-bugs channel on the Discord server.
