### ISSUE TITLE
Phantasmal Force

### ISSUE THREAD

**Issue by SplashCity46** [Orcpub/orcpub#382]
So wasn't sure to put this in this section or the feature section. I just find it odd that the spell "Phantasmal Force", a LV 2 spell in the PHB is doesn't appear on the wizard list in the character builder.

**Comment by codeGlaze** [comment]
It looks like *Phantasmal Force* is not SRD, which is super weird. I didn't realize they kept spells from the PHB out of the SRD.

You can join our discord via the link of [reddit](https://www.reddit.com/r/dungeonmastersvault/). Someone there should be able to help you brew the content you want. :)

Closing this because it's not something we can add to the site.
