### ISSUE TITLE
Wrong number of spells to select

### ISSUE THREAD

**Issue by 4sfaloth** [Orcpub/orcpub#538]
**Describe the bug**

Recently I went to update one of my characters, a Tiefling Ranger, up to Lvl5. At Lvl5 he should be entitled to choose 4 ranger spells, and that is indeed what the spell selection menu **_says_**. However, it only lets me select 2 (see screenshot below). I suspect this may be related to the fact that I have two extra spells due to being Tiefling, but is definitely a bug

**To Reproduce**

There are probably other ways to see the same bug, but in my case
1. Create a Tiefling Ranger 
2. Level up to lvl5
3. Try to select the 4 spells you are entitled to

**Expected behavior**

Should be able to select 4 spells, can only select 2

**Screenshots**

![WhatsApp Image 2021-08-30 at 08 33 05](https://user-images.githubusercontent.com/8202087/131303064-80f2747e-2d64-4fd9-bceb-88efa782c274.jpeg)

**Comment by DivertedCircle** [comment]
I cannot replicate this and don't believe it is a problem with the website. I suspect 1 of 2 things has happened.
1. You're using a custom file for the Ranger class which was made incorrectly. You'll have to fix this yourself, or contact whoever made the file.
2. You previously had this character set to a higher level and had 3rd level or higher spells selected. You've since set the character to a lower level and the higher levels spells disappeared from the list, but the site still thinks they're selected. In this case, set the character to a higher level again, unselect the spells, then lower the level again.

**Comment by 4sfaloth** [comment]
@DivertedCircle thanks get picking this up. Based on your comment I took another look and what happened is that on the machine I was using I had forgotten to import some custom content which included extra spells, 2 of which I had selected. So I couldn't see those 2 spells; after re-importing the content everything looks fine.

I am sorry for the false alarm, and thanks for the quick response
