### ISSUE TITLE
Severe Content List Bug

### ISSUE THREAD

**Issue by KenkuQuail** [Orcpub/orcpub#575]
Created Subraces disappear even when saved to a computer
- when saving over a subrace I created, all of my subraces vanished from my content list in spite of my having saved them to my computer

1. Create five subraces
2. edit a subrace
3. save a new subrace
4. return to the Content list

Content list should show that no subraces exist. Attempting to create a character of the race the subrace is connected to shouldn't show the subrace as an option

**Screenshots**

I have no screenshots from before this incident, unfortunately, and the only change is that the subraces I created are not there.

**Desktop (please complete the following information):**

 - OS: Microsoft
 - Browser Chrome
 - Version 2022

- Reloading the page and logging out and back in do not restore the created subraces

**Comment by DivertedCircle** [comment]
Are these subraces the only thing you have loaded in your My Content screen? If so, I suspect this is either a bug in the naming of the subraces you made which is causing the website to glitch (in which case scrap what you have loaded in My Content and start over) or more likely, your browser is wiping your saved content because your browser memory is full. Try clearing your browser cache, then creating the subraces again and see if that solves the problem.

**Comment by KenkuQuail** [comment]
No i had a few different things loaded and the subraces were the only ones
that disappeared. I had them downloaded to my computer, and was able to
bring back three of them, but for some reason the other two weren't coming
back and my other two saves that should have had them didn't have any of my
subraces, so I had to remake the last two

**Comment by DivertedCircle** [comment]
That definitely sounds like your subraces bugged then and isn't an issue with the sire per se. If it happens again you'll need to provide more information but I suspect you should be able to remake the subraces without issue.

**Comment by KenkuQuail** [comment]
Will do. Thank you
