### ISSUE TITLE
Tickbox bug

### ISSUE THREAD

**Issue by HaleyGozdanovic** [Orcpub/orcpub#588]
Whenever I try to make something on DMV, all the boxes are automatically checked, and I can't uncheck them.

I don't have any specific way to reproduce the behavior, it's just whenever I try to make anything.

**Expected behavior**

I haven't clicked anything, so I'd expect the boxes to not be clicked.

**Screenshots**

![bug](https://user-images.githubusercontent.com/63872960/224927201-19ed0d9f-1074-4578-bd3d-497331e63cc4.png)

**Desktop (please complete the following information):**

 - OS: Windows 11
 - Browser Opera GX
 - Version 96.0.4693.59

**Additional context**

I haven't clicked any boxes before screenshotting. Clicking on them does nothing.

**Comment by DivertedCircle** [comment]
Does the error occur in other browsers as well, or just Opera?
Does it always occur in Opera or is it intermittent?
Are you using any browser extensions, such as an adblocker?
If yes, does the problem go away with the extension disabled?

**Comment by closedragonfly** [comment]
Turn off forced dark mode for DMV.

**Comment by codeGlaze** [comment]
> Turn off forced dark mode for DMV.

closedragonfly has the right suggestion.
I believe it's a browser or react issue with forced dark mode, so disabling it should solve the problem. Especially since our site already defaults to a dark theme.

If someone finds a fix we can shim into the site, I'm all ears, but via googling I've seen people mention it about other websites too.

Closing this until/unless something new comes up
