### ISSUE TITLE
character sheets will not load

### ISSUE THREAD

**Issue by parker11111** [Orcpub/orcpub#592]
site just finished maintenance and i wanted to check some characters my friends had made, but whenever i tried to look at a character sheet in the editor or otherwise, the site went to a black screen

Steps to reproduce the behaviour:
1. go to character list
2. click the "open" button on the far right

 - OS: windows 10
 - Browser: opera gx
 - Version: i dont know what this is referring to sorry

**Comment by datdamnzotz** [comment]
Most of the time if you getting a black screen it’s because you have Adblockers turned on.

If you hit F12 and check the Browser Console and see this:
![image](https://github.com/Orcpub/orcpub/assets/3913859/0002427b-e06b-4b83-992a-f94bedb1e9aa)

Chances are It’s adblockers.
* Log off and back in.
* Turn off your adblockers, CNTRL+F5 refresh
* Open in an incognito mode with no homebrew loaded, CNTRL+F5 refresh
* Only load the homebrew needed for your current character, CNTRL+F5 refresh
